version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run: |
             sudo apt-get update 
             sudo apt-get install cppcheck 
            
      - run: |
             sudo apt-get update 
             sudo apt-get install clang-format 
             
      - run: |
             sudo apt-get update
             sudo apt-get install valgrind
             
      - run: |
             sudo apt-get update
             sudo apt-get install build-essential
             
      - run: |
             sudo apt-get update
             sudo apt-get install g++
             
      - run: |
             sudo apt-get update
             sudo apt-get install cmake
      - run: |
             sudo apt-get update
             sudo apt-get install libboost-all-dev
          
      - run: |
             sudo apt update
             sudo apt-get install libgtest-dev
             cd /usr/src/gtest
             sudo cmake .
             sudo make
             sudo cp -R /usr/src/gtest/lib/*.a /usr/lib/x86_64-linux-gnu
             
      - run: |
             sudo apt-get update
             sudo apt-get install gcovr

      - run: |
             cppcheck ./*/*.cpp ./*/*.hpp

       #Install postgresql and create user and db
      - run: |
             sudo apt-get update
             sudo apt-get install postgresql
             sudo -u postgres
             pg_ctlcluster 12 main start
             service postgresql start
             psql
             CREATE USER tester WITH PASSWORD 'test_password';
             CREATE DATABASE test_db;  
             GRANT ALL PRIVILEGES ON DATABASE "test_db" to tester;
             
             CREATE USER server WITH PASSWORD 'server_password';
             CREATE DATABASE BAUMAN_TINDER;  
             GRANT ALL PRIVILEGES ON DATABASE "BAUMAN_TINDER" to server;

             exit
             exit
       
       #Install libpqxx
      - run: |
             cd ~
             git clone https://github.com/jtv/libpqxx.git
             ./configure
             make -j4
             sudo make install

      - run: |
             cd ~
             git clone https://github.com/jtv/libpqxx.git
             ./configure
             make -j4
             sudo make install


